// Code generated by mockery v2.51.0. DO NOT EDIT.

package logger_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	slog "log/slog"
)

// LoggerMock is an autogenerated mock type for the Logger type
type LoggerMock struct {
	mock.Mock
}

// Debug provides a mock function with given fields: ctx, message, fields
func (_m *LoggerMock) Debug(ctx context.Context, message string, fields ...slog.Attr) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Error provides a mock function with given fields: ctx, message, fields
func (_m *LoggerMock) Error(ctx context.Context, message string, fields ...slog.Attr) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Info provides a mock function with given fields: ctx, message, fields
func (_m *LoggerMock) Info(ctx context.Context, message string, fields ...slog.Attr) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Warn provides a mock function with given fields: ctx, message, fields
func (_m *LoggerMock) Warn(ctx context.Context, message string, fields ...slog.Attr) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, message)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// NewLoggerMock creates a new instance of LoggerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerMock {
	mock := &LoggerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
